// Daily motivational quotes for Konsensi Budget Beheer
// Each day of the year gets a unique quote based on the day number

const dailyQuotes = [
  "Kleine stappen leiden tot grote resultaten.",
  "Elke euro die je bespaart, brengt je dichter bij financiële vrijheid.",
  "Financiële discipline is de sleutel tot een zorgeloze toekomst.",
  "Je bent sterker dan je schulden.",
  "Elk bedrag dat je aflost, is een overwinning.",
  "Geduld en doorzettingsvermogen winnen het spel.",
  "Je financiële reis begint met één stap.",
  "Blijf gefocust op je doelen, niet op je schulden.",
  "Vooruitgang is vooruitgang, hoe klein ook.",
  "Jouw toekomst is het waard om voor te vechten.",
  "Elke dag is een nieuwe kans om beter te doen.",
  "Financiële vrijheid is geen droom, het is een keuze.",
  "Je bent de baas over je geld, niet andersom.",
  "Kleine offers nu, grote vrijheid later.",
  "Je bent op de goede weg, blijf doorgaan!",
  "Elk budget is een plan naar succes.",
  "Discipline vandaag, vrijheid morgen.",
  "Je hebt de kracht om je financiën te beheersen.",
  "Vooruitgang, niet perfectie.",
  "Jouw toekomst begint nu.",
  "Elke schuld die je aflost, is een stap naar vrijheid.",
  "Blijf gefocust, blijf gemotiveerd.",
  "Je bent sterker dan je denkt.",
  "Kleine stappen, grote dromen.",
  "Financiële vrijheid is binnen handbereik.",
  "Jouw doelen zijn de moeite waard.",
  "Blijf sparen, blijf dromen.",
  "Je bent op weg naar een betere toekomst.",
  "Elke euro telt.",
  "Discipline is de brug tussen doelen en prestaties.",
  "Je hebt dit onder controle.",
  "Blijf geloven in jezelf.",
  "Jouw financiële toekomst ziet er stralend uit.",
  "Elke dag dichter bij je doel.",
  "Je bent een financiële held in wording.",
  "Blijf doorzetten, het is het waard.",
  "Jouw inspanningen worden beloond.",
  "Financiële vrijheid is een reis, geen bestemming.",
  "Je maakt de juiste keuzes.",
  "Blijf gefocust op wat belangrijk is.",
  "Jouw toekomst dankt je.",
  "Elke stap telt.",
  "Je bent op de goede weg.",
  "Blijf investeren in jezelf.",
  "Jouw financiële doelen zijn haalbaar.",
  "Blijf gemotiveerd, blijf sterk.",
  "Je hebt de tools om te slagen.",
  "Elke dag is een nieuwe kans.",
  "Jouw succes begint hier.",
  "Blijf geloven, blijf groeien.",
  "Je bent een inspiratie.",
  "Financiële wijsheid komt met discipline.",
  "Blijf sparen voor je dromen.",
  "Je hebt de kracht om te veranderen.",
  "Elke euro is een investering in je toekomst.",
  "Blijf gefocust op vooruitgang.",
  "Jouw inspanningen zijn waardevol.",
  "Je bent dichter bij je doel dan gisteren.",
  "Blijf positief, blijf vooruitgaan.",
  "Jouw financiële vrijheid is nabij.",
  "Elke beslissing telt.",
  "Je hebt dit!",
  "Niemand verdient het om schulden te hebben.",
  "Het betalen van schulden is een marathon en geen race.",
  "Jouw financiële toekomst ligt in jouw handen.",
  "Elke cent die je bespaart, is winst.",
  "Je bent sterker dan je angsten.",
  "Blijf consistent, blijf groeien.",
  "Jouw budget is jouw kompas.",
  "Financiële stabiliteit begint vandaag.",
  "Je bent de architect van je eigen toekomst.",
  "Elke maand zonder schuld is een overwinning.",
  "Blijf dromen, blijf werken aan je doelen.",
  "Jouw geld werkt voor jou.",
  "Financiële vrijheid is het resultaat van kleine dagelijkse keuzes.",
  "Je bent niet alleen op deze reis.",
  "Elke betaling brengt je dichter bij vrijheid.",
  "Blijf gefocust op de lange termijn.",
  "Jouw financiële welzijn is een prioriteit.",
  "Je hebt de moed om je schulden aan te pakken.",
  "Elke dag is een stap in de goede richting.",
  "Blijf optimistisch over je financiële toekomst.",
  "Jouw doorzettingsvermogen zal worden beloond.",
  "Financiële discipline is een gave aan jezelf.",
  "Je bent op weg naar financiële onafhankelijkheid.",
  "Elke euro die je niet uitgeeft, is een euro gespaard.",
  "Blijf trots op je vooruitgang.",
  "Jouw financiële doelen zijn binnen bereik.",
  "Je hebt de kracht om je leven te veranderen.",
  "Elke maand brengt nieuwe kansen.",
  "Blijf geduldig met jezelf.",
  "Jouw inspanning vandaag, zorgt voor vrijheid morgen.",
  "Financiële stabiliteit is geen toeval.",
  "Je bent bezig met iets geweldigs.",
  "Elke betaling is een investering in je rust.",
  "Blijf consequent met je budget.",
  "Jouw toekomst is helderder dan je denkt.",
  "Je hebt de controle over je financiën.",
  "Elke keuze die je maakt, telt.",
  "Blijf gefocust op wat echt belangrijk is.",
  "Jouw financiële reis is uniek en waardevol.",
  "Je bent op de goede weg naar vrijheid.",
  "Elke dag zonder nieuwe schuld is winst.",
  "Blijf werken aan je dromen.",
  "Jouw financiële welzijn verdient aandacht.",
  "Je hebt de kracht om door te gaan.",
  "Elke stap vooruit is vooruitgang.",
  "Blijf geloven in je mogelijkheden.",
  "Jouw toekomst ziet er rooskleurig uit.",
  "Financiële vrijheid begint met een beslissing.",
  "Je bent niet gedefinieerd door je schulden.",
  "Elke euro die je aflost, is een overwinning op jezelf.",
  "Blijf streven naar financiële balans.",
  "Jouw inspanningen worden gezien en gewaardeerd.",
  "Je hebt de wijsheid om goede keuzes te maken.",
  "Elke maand is een nieuwe start.",
  "Blijf gefocust op je financiële gezondheid.",
  "Jouw toekomst dankt je voor de keuzes van vandaag.",
  "Je bent bezig met de beste investering: jezelf.",
  "Elke betaling is een stap dichter bij je dromen.",
  "Blijf positief, zelfs als het moeilijk is.",
  "Jouw financiële reis is het waard.",
  "Je hebt de moed om te blijven doorgaan.",
  "Elke dag breng je dichter bij financiële vrijheid.",
  "Blijf vasthouden aan je doelen.",
  "Jouw toekomst is in goede handen: de jouwe.",
  "Financiële stabiliteit is een cadeau aan jezelf.",
  "Je bent sterker dan je uitdagingen.",
  "Elke euro gespaard is een euro verdiend.",
  "Blijf werken aan je financiële welzijn.",
  "Jouw inspanningen zullen vruchten afwerpen.",
  "Je hebt de kracht om te overwinnen.",
  "Elke stap is een stap in de goede richting.",
  "Blijf geloven in een betere financiële toekomst.",
  "Jouw doelen zijn haalbaar en realistisch.",
  "Je bent bezig met iets waardevols.",
  "Elke maand zonder schuld voelt als vrijheid.",
  "Blijf gefocust op wat je kunt beïnvloeden.",
  "Jouw financiële toekomst is stralend.",
  "Je hebt de discipline om te slagen.",
  "Elke keuze brengt je dichter bij je doel.",
  "Blijf investeren in je toekomst.",
  "Jouw financiële reis verdient respect.",
  "Je bent op weg naar iets moois.",
  "Elke dag is een kans om beter te doen.",
  "Blijf gemotiveerd, zelfs als het zwaar is.",
  "Jouw toekomst is de moeite waard.",
  "Financiële vrijheid is jouw recht.",
  "Je bent bezig met de beste beslissing van je leven.",
  "Elke betaling is een investering in rust.",
  "Blijf vasthouden aan je visie.",
  "Jouw inspanningen zijn niet voor niets.",
  "Je hebt de kracht om te veranderen.",
  "Elke maand is een stap dichter bij vrijheid.",
  "Blijf positief over je financiële reis.",
  "Jouw toekomst begint met de keuzes van nu.",
  "Je bent sterker dan je schulden suggereren.",
  "Elke euro aflossen is een overwinning.",
  "Blijf gefocust op de grote winnende doelen.",
  "Jouw financiële welzijn is essentieel.",
  "Je hebt de wijsheid om goede beslissingen te nemen.",
  "Elke dag brengt nieuwe mogelijkheden.",
  "Blijf werken aan je dromen, elke dag opnieuw.",
  "Jouw toekomst dankt je voor je doorzettingsvermogen.",
  "Financiële stabiliteit is geen toeval, maar een keuze.",
  "Je bent bezig met iets waardevols en belangrijks.",
  "Elke betaling brengt rust en vrijheid dichterbij.",
  "Blijf consistent in je inspanningen.",
  "Jouw financiële toekomst ziet er rooskleurig uit.",
  "Je hebt de controle, gebruik die kracht.",
  "Elke keuze die je maakt, maakt het verschil.",
  "Blijf gefocust op lange termijn succes.",
  "Jouw financiële reis is uniek en mooi.",
  "Je bent op de goede weg, blijf doorgaan.",
  "Elke dag zonder nieuwe schuld is pure winst.",
  "Blijf werken aan je financiële doelen.",
  "Jouw welzijn verdient alle aandacht.",
  "Je hebt de innerlijke kracht om door te gaan.",
  "Elke stap vooruit is echte vooruitgang.",
  "Blijf geloven in jezelf en je mogelijkheden.",
  "Jouw toekomst is stralend en vol kansen.",
  "Financiële vrijheid begint met één beslissing.",
  "Je bent méér dan je schulden.",
  "Elke euro die je aflost is een persoonlijke overwinning.",
  "Blijf streven naar balans en welzijn.",
  "Jouw inspanningen worden opgemerkt en gewaardeerd.",
  "Je hebt de wijsheid die nodig is.",
  "Elke nieuwe maand is een frisse start.",
  "Blijf gefocust op je financiële gezondheid.",
  "Jouw toekomst dankt je voor elke goede keuze.",
  "Je investeert in jezelf en dat is de beste investering.",
  "Elke betaling is een stap richting je dromen.",
  "Blijf positief, ook in moeilijke tijden.",
  "Jouw reis is waardevol en belangrijk.",
  "Je hebt de moed om vol te houden.",
  "Elke dag brengt je dichter bij financiële rust.",
  "Blijf vasthouden aan wat belangrijk is.",
  "Jouw toekomst ligt veilig in jouw handen.",
  "Financiële stabiliteit is een geschenk aan jezelf.",
  "Je bent sterker dan elke uitdaging.",
  "Elke gespaarde euro is winst.",
  "Blijf actief werken aan je welzijn.",
  "Jouw inspanningen leiden tot resultaten.",
  "Je hebt de kracht om obstakels te overwinnen.",
  "Elke stap telt, hoe klein ook.",
  "Blijf geloven in een betere toekomst.",
  "Jouw doelen zijn binnen handbereik.",
  "Je bent bezig met iets geweldigs.",
  "Elke maand zonder extra schuld is vrijheid.",
  "Blijf gefocust op wat je kunt controleren.",
  "Jouw financiële toekomst straalt.",
  "Je hebt de discipline die nodig is voor succes.",
  "Elke keuze brengt je dichter bij je doel.",
  "Blijf investeren in een betere morgen.",
  "Jouw financiële reis verdient waardering.",
  "Je bent onderweg naar iets moois.",
  "Elke dag biedt nieuwe kansen.",
  "Blijf gemotiveerd, ook als het lastig wordt.",
  "Jouw toekomst is alle moeite waard.",
  "Financiële vrijheid is jouw geboren recht.",
  "Je maakt de beste keuzes voor jezelf.",
  "Elke betaling is een investering in innerlijke rust.",
  "Blijf vasthouden aan je visie en dromen.",
  "Jouw inspanningen hebben zin en betekenis.",
  "Je hebt de kracht om blijvend te veranderen.",
  "Elke nieuwe maand brengt nieuwe vrijheid.",
  "Blijf positief over je financiële pad.",
  "Jouw toekomst wordt gevormd door nu.",
  "Je bent sterker dan wat de cijfers laten zien.",
  "Elke aflossing is een persoonlijke triomf.",
  "Blijf gericht op je grootste doelen.",
  "Jouw financiële welzijn is cruciaal.",
  "Je hebt de wijsheid voor slimme keuzes.",
  "Elke dag opent nieuwe deuren.",
  "Blijf werken aan wat belangrijk is.",
  "Jouw toekomst dankt je voor je volharding.",
  "Financiële stabiliteit komt door bewuste keuzes.",
  "Je bent bezig met iets waardevols.",
  "Elke betaling brengt vrede dichterbij.",
  "Blijf consistent en gedisciplineerd.",
  "Jouw financiële pad is veelbelovend.",
  "Je hebt meer controle dan je denkt.",
  "Elke keuze heeft impact.",
  "Blijf denken aan de lange termijn.",
  "Jouw reis is uniek en betekenisvol.",
  "Je doet het goed, blijf volhouden.",
  "Elke dag zonder extra schuld is vooruitgang.",
  "Blijf bouwen aan je financiële toekomst.",
  "Jouw welzijn staat voorop.",
  "Je hebt innerlijke kracht.",
  "Elke stap is echte vooruitgang.",
  "Blijf in jezelf geloven.",
  "Jouw toekomst is vol mogelijkheden.",
  "Financiële vrijheid begint vandaag.",
  "Je bent meer dan getallen op papier.",
  "Elke aflossing is een zege.",
  "Blijf streven naar evenwicht.",
  "Jouw inspanningen worden gewaardeerd.",
  "Je hebt wijsheid in overvloed.",
  "Elke maand is een nieuwe kans.",
  "Blijf zorgen voor je financiële gezondheid.",
  "Jouw toekomst dankt je nu al.",
  "Investeren in jezelf loont altijd.",
  "Elke betaling brengt dromen dichterbij.",
  "Blijf positief en volhardend.",
  "Jouw reis is de moeite waard.",
  "Je hebt moed in overvloed.",
  "Elke dag is een stap voorwaarts.",
  "Blijf vasthouden aan wat telt.",
  "Jouw toekomst is in veilige handen.",
  "Financiële stabiliteit is zelfzorg.",
  "Je bent sterker dan je denkt.",
  "Elke euro gespaard telt mee.",
  "Blijf werken aan jouw welzijn.",
  "Jouw inspanningen dragen vruchten.",
  "Je hebt de kracht om te slagen.",
  "Elke stap is belangrijk.",
  "Blijf geloven in betere tijden.",
  "Jouw doelen zijn haalbaar.",
  "Je bent bezig met iets waardevols.",
  "Elke maand brengt meer vrijheid.",
  "Blijf gefocust op jouw pad.",
  "Jouw toekomst is stralend.",
  "Je hebt wat nodig is.",
  "Elke keuze maakt verschil.",
  "Blijf bouwen aan morgen.",
  "Jouw reis verdient respect.",
  "Je bent op weg naar succes.",
  "Elke dag telt.",
  "Blijf gemotiveerd en sterk.",
  "Jouw toekomst wacht op je.",
  "Financiële vrijheid is voor iedereen.",
  "Je maakt slimme keuzes.",
  "Elke betaling is vooruitgang.",
  "Blijf vasthouden aan je dromen.",
  "Jouw inspanningen hebben betekenis.",
  "Je hebt echte kracht.",
  "Elke maand is een stap vooruit.",
  "Blijf positief en gericht.",
  "Jouw toekomst wordt nu gevormd.",
  "Je bent sterker dan cijfers.",
  "Elke aflossing is winst.",
  "Blijf richten op je doelen.",
  "Jouw welzijn is belangrijk.",
  "Je hebt wijsheid en kracht.",
  "Elke dag biedt kansen.",
  "Blijf werken aan je toekomst.",
  "Jouw pad is waardevol.",
  "Je doet het uitstekend.",
  "Elke stap vooruit telt.",
  "Blijf in jezelf geloven.",
  "Jouw toekomst is helder.",
  "Financiële rust komt eraan.",
  "Je bent op de goede weg.",
  "Elke keuze brengt je verder.",
  "Blijf gemotiveerd en doorgaan.",
  "Jouw reis is uniek.",
  "Je hebt alles in je.",
  "Elke dag is vooruitgang.",
  "Blijf streven naar balans.",
  "Jouw toekomst is de moeite waard.",
  "Je bent een financiële winnaar in wording.",
  "Elke euro is een stap naar vrijheid.",
  "Blijf geloven, blijf volhouden.",
  "Jouw inspanningen maken het verschil.",
  "Je bent sterker dan je ooit dacht.",
  "Elke betaling is een zege op jezelf.",
  "Blijf gefocust en gedisciplineerd.",
  "Jouw toekomst dankt je elke dag.",
  "Financiële vrijheid is geen mythe, het is jouw realiteit.",
  "Je hebt de sleutel tot succes al in handen.",
  "Elke dag zonder schuld is een geschenk.",
  "Blijf werken, blijf dromen, blijf groeien.",
  "Jouw financiële verhaal wordt steeds mooier.",
  "Je bent de held van je eigen verhaal.",
  "Elke stap die je zet, is een stap naar licht.",
  "Blijf optimistisch, blijf sterk, blijf jezelf.",
  "Jouw toekomst is stralend en vol potentieel.",
  "Financiële wijsheid groeit met elke keuze die je maakt.",
];

/**
 * Get the daily motivational quote based on current date
 * Same quote shows all day, changes at midnight
 * @returns {string} The motivational quote for today
 */
export function getDailyQuote() {
  const today = new Date();
  // Get day of year (1-365/366)
  const start = new Date(today.getFullYear(), 0, 0);
  const diff = today - start;
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);

  // Use modulo to cycle through quotes
  const quoteIndex = dayOfYear % dailyQuotes.length;

  return dailyQuotes[quoteIndex];
}

export default dailyQuotes;
